### ISSUE TITLE
[BUG]: Game Over Screen 

### ISSUE THREAD

**Issue by LouieMarcou** [Blue-Square-Legion/Keito-Yarn-Game#51] opened 2024-08-05 20:09 UTC
### Description of the bug

If you lose the game over screen shows up but you are still able to move the aim of the yarn ball. Might want to double check if it still happens if you win.

### Steps To Reproduce

1. Go to YarnBallAttributeTesting branch
2. Go to in game scene or kitchen scene
3. Toss yarn balls until you run out
4. Move mouse during the game over screen

**Comment by KallenXCC** [comment] 2024-08-18 19:20
Closing as duplicate of #52 , this error only occurs when you are able to pause during the game over/level complete screen which we are disabling

**Closed by KallenXCC** 2024-08-18 19:20 UTC
Labels: bug
